defaults:
  - _self_
  - models: 2G-GCN_stage1_mphoi_2025
  - data: mphoi_45_2025 #mphoi, cad120, bimanual
hydra:
  run:
    dir: outputs_hiergat/${data.name}/${models.metadata.model_name}/${models.logging.checkpoint_name}
resources:
  use_gpu: true
  num_threads: 32
